- name: Install epel release
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: copier rpm file sur le serveur
  copy:
     src: files/remi-release-7.rpm
     dest: /tmp_app/mediawiki/package.rpm

- name: Install rpm
  command: rpm -Uvh /tmp_app/mediawiki/package.rpm
  ignore_errors: true

- name: install repo
  yum:
    name: "{{ item }}"
    enablerepo: remi-php74
    state: present
  loop:
    - php
    - php-xml
    - php-soap
    - php-xmlrpc
    - php-mbstring
    - php-json
    - php-gd
    - php-mcrypt
    - php-mysql
    - php74-php-intl
  ignore_errors: true
  notify: restart httpd
