- name: Install epel release
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: copier rpm file sur le serveur
  copy:
     src: files/remi-release-7.rpm
     dest: /tmp_app/mediawiki/package.rpm

- name: Install php74
  command: yum --enablerepo=remi-php74 install php php-xml php-soap php-xmlrpc php-mbstring php-json php-gd php-mcrypt.x86_64 php-mysql.x86_64 php74-php-intl.x86_64 -y
