- name: Create a logical volume log
  lvol:
    vg: centos
    lv: log
    size: 1024

- name: Formater log en xfs
  filesystem:
    fstype: xfs
    dev: /dev/centos/log

- name: Mount log
  mount:
    path: /var/projects/mediawiki
    src: /dev/centos/log
    fstype: xfs
    state: mounted

- name: Create a logical volume appli
  lvol:
    vg: centos
    lv: appli
    size: 2048

- name: Formater appli en xfs
  filesystem:
    fstype: xfs
    dev: /dev/centos/appli

- name: Mount appli
  mount:
    path: /appli/mediawiki
    src: /dev/centos/appli
    fstype: xfs
    state: mounted

- name: Create a logical volume tmp
  lvol:
    vg: centos
    lv: tmp
    size: 2048

- name: Formater tmp en xfs
  filesystem:
    fstype: xfs
    dev: /dev/centos/tmp

- name: Mount tmp
  mount:
    path: /tmp_app/mediawiki/
    src: /dev/centos/tmp
    fstype: xfs
    state: mounted

- name: Create a logical volume data
  lvol:
    vg: centos
    lv: data
    size: 2048

- name: Mount data
  mount:
    path: /home/mediawiki/data
    src: /dev/centos/data
    fstype: xfs
    state: mounted
