
- name: installer apache et php
  package:
    name:
      - httpd
      - php
      - php-xml
      - php-mariadb
      - php-mysql
      - php-gd
      - php-intl
      - php-mbstring
      - firewalld
    state: present
    update_cache: yes

#- name: droit d'ecriture sur le dossier apache
#  file:
#    path: /var/www/html
#    state: directory
#    mode: '0755'

#- name: supprimer le fichier  index
#  file:
#    path: /var/www/html/index.html
#    state: absent

#- name: upload web app source
#  copy:
#    src: app/
#    dest: /var/www/html/

#- name: deploy php database config
  template:
    src: "/templates/db-config.php.j2"
    dest: "/var/www/html/db-config.php"

#- name: ensure apache service is start
#  service:
#    name: apache2
#    state: started
#    enabled: yes
