- name: Install PHP et apache2
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
      - httpd
      - php
      - php-xml
      - php-mariadb
      - php-mysql
      - php-gd
      - php-intl
      - php-mbstring
      - firewalld
