- name: Install PHP et apache2
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
      - httpd
      - php
      - php-xml
      - php-mariadb
      - php-mysql
      - php-gd
      - php-intl
      - php-mbstring
      - firewalld
- name: enable service httpd and ensure it is not masked
  systemd:
    name: httpd
    enabled: yes
    masked: no
