- name: Install mariadb
  package:
    name: mariadb-server
    state: present
    update_cache: yes
- name: enable service mariadb and ensure it is not masked
  systemd:
    name: mariadb-server
    enabled: yes
    masked: no
