- name: importe base de données
  command: php /appli/projects/mediawiki/httpd/wiki_devops/maintenance/importDump.php /appli/mediawiki/LIVR/01.00.00/INPUT_GROUPED/Package_1/Donnees.xml

- name: script valide la base de données
  command: php /appli/projects/mediawiki/httpd/wiki_devops/maintenance/rebuildrecentchanges.php

- name: dézipper les images
  unarchive:
    src: /appli/mediawiki/LIVR/01.00.00/INPUT_GROUPED/Package_1/dump_image.tar.gz
    dest: /tmp_app/mediawiki

- name: importer les images dans la base de donnees
  command: php /appli/projects/mediawiki/httpd/wiki_devops/maintenance/importImages.php /appli/mediawiki/LIVR/01.00.00/INPUT_GROUPED/Package_1/images
